### ISSUE TITLE
Data Pack Editor does not save modifiers on weapons

### ISSUE THREAD

**Issue by adonutwithsprinklez** [adonutwithsprinklez/CodeNameEmpty#130]
It appears that the Data Pack Editor is not saving any modifiers to weapons.

Error Log:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/nicolashomsher/Documents/codenameEmptyRepo/CodeNameEmpty/src/dataPackEditor.py", line 1300, in saveWeapon
    if (self.wepModChance.get.strip()):
AttributeError: 'function' object has no attribute 'strip'
```

**Comment by adonutwithsprinklez** [comment]
Addressed in #132
